import WeatherApp from "../core/WeatherApp";
import LanguageManager from "../localization/LanguageManager";
type WeatherAppUIConfig = {
    weatherApp: WeatherApp;
    languageManager: LanguageManager;
    loadingPageId: string;
    errorPageId: string;
    errorPageMessageId: string;
    weatherAppPageId: string;
    languageSelectButtonId: string;
    languageSelectButtonFlagImageId: string;
    languageSelectButtonTextId: string;
    languageSelectItemsContainerId: string;
    languageSelectEnglishButtonId: string;
    languageSelectCzechButtonId: string;
    languageSelectSlovakButtonId: string;
    languageSelectGermanButtonId: string;
    locationSearchBarInputId: string;
    locationSearchBarResultsContainerId: string;
    currentWeatherHeadingId: string;
    forecastHeadingId: string;
    currentWeatherFeelsLikeLabelId: string;
    currentWeatherHumidityLabelId: string;
    currentWeatherWindLabelId: string;
    currentLocationNameId: string;
    currentWeatherLoadingIconId: string;
    currentWeatherContentContainerId: string;
    currentWeatherImageId: string;
    currentWeatherTemperatureValueElementId: string;
    currentWeatherDescriptionId: string;
    currentWeatherFeelsLikeValueElementId: string;
    currentWeatherHumidityValueElementId: string;
    currentWeatherWindValueElementId: string;
    forecastLoadingIconId: string;
    forecastContentContainerId: string;
    forecastTemperatureButtonId: string;
    forecastFeelsLikeButtonId: string;
    forecastPrecipitationButtonId: string;
    forecastHumidityButtonId: string;
    forecastWindButtonId: string;
    daysNavigationId: string;
    graphCanvasId: string;
    graphTimelineElementId: string;
};
declare class WeatherAppUI {
    private pagesToggle;
    private languageLoaded;
    constructor(config: WeatherAppUIConfig);
    private onDataLoadingError;
    private onLanguageChange;
    private getElementById;
}
export default WeatherAppUI;
